title: liwolf's blog
author: liwolf
email: 2608634952hui@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  This is a personal blog.
show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  name: liwolf
  tagline: Jnu Student
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content
  search: true # set to true to enable searchbar
  dark_mode: true # set to true to add dark mode toggle
  portfolio_image: "assets/portfolio.png" # the path from the base directory of the site to the image to display (no / at the start)
  html_lang: "en" # set the lang attribute of the <html> tag for the pages. See here for a list of codes: https://www.w3schools.com/tags/ref_country_codes.asp
  condensed_mobile:
    - home
    - page
    - post
    - moods
  # generate social links in footer
  navigation: 
    - title: My Mood
      url: /moods
  social_links:
    # twitter: samarsault
    github:  xiaohuihuiL
    bilibili: 397704847/fans/follow?spm_id_from=333.999.0.0
    # linkedIn: in/samarsault
    #dribbble: jekyll
    #flickr:   jekyll
    #instagram: jekyll
    #pinterest: jekyll
    #youtube: jekyll
    #facebook: jekyll
    #soundcloud: jekyll
    #telegram: jekyll
    #gitlab: jekyll
    #email: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
remote-theme: plainwhite

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
# ./usr/local/Cellar/ruby@3.0/3.0.6_1/bin/bundle
# bundle exec jekyll serve
